language: generic

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11

matrix:
  include:
     - os: osx
       osx_image: xcode8.2
     - os: linux
       sudo: false

script:
 - ./setup.sh
 - ./initialize.sh
 - ./run.sh
 - ./stop.sh
 # should be able to cleanup all data and re-initialize and run again cleanly
 - ./cleanup.sh
 - ./initialize.sh
 - ./run.sh
 - ./stop.sh
