language: generic

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - libstdc++6 # upgrade libstdc++ on linux to support C++11

matrix:
  include:
     - os: osx
       osx_image: xcode7.3
       compiler: clang
     - os: linux
       sudo: false

install:
 - ./install.sh

script:
 - ./install.sh
 - ./stop.sh
